version: '2.1'

services:
  backend:
    image: brandquad_test_task
    build: .
    volumes:
      - .:/app
  db:
    image: postgres
  adminer:
    image: adminer
    ports:
      - 8080:8080
  frontend:
    build: ./frontend/
    ports:
      - 8000:8000