version: '2.1'

services:
  brandquad_test_task:
    image: brandquad_test_task
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
  db:
    image: postgres
  adminer:
    image: adminer
    ports:
      - 8080:8080

