# Generated by Django 2.1.5 on 2019-01-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateTimeField()),
                ('http_method', models.CharField(max_length=7)),
                ('uri', models.CharField(max_length=200)),
                ('status_code', models.CharField(max_length=3)),
                ('size_of_response', models.IntegerField()),
            ],
        ),
    ]
