# Generated by Django 2.1.5 on 2019-01-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apache_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='uri',
            field=models.CharField(max_length=500),
        ),
    ]
